/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Hendrew
 */
public class tela_cadastro extends javax.swing.JFrame {

    /**
     * Creates new form tela_cadastro
     */
    public tela_cadastro() {
        initComponents();
        
       
       btn_master_inicio.setContentAreaFilled(false); //to make the content area transparent
       btn_master_duvidas.setContentAreaFilled(false); //to make the content area transparent
       btn_master_cadastro.setContentAreaFilled(false); //to make the content area transparent
       btn_master_vendas.setContentAreaFilled(false); //to make the content area transparent
       btn_master_clientes.setContentAreaFilled(false); //to make the content area transparent
       btn_master_cadastro_cliente.setContentAreaFilled(false); //to make the content area transparent


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCadVendedor = new javax.swing.JDesktopPane();
        btn_master_duvidas = new javax.swing.JButton();
        btn_master_vendas = new javax.swing.JButton();
        btn_master_clientes = new javax.swing.JButton();
        btn_master_inicio = new javax.swing.JButton();
        btn_master_cadastro = new javax.swing.JButton();
        btn_master_cadastro_cliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Cima_Azul = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Solar Plus™");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 850));
        setResizable(false);
        getContentPane().setLayout(null);

        jCadVendedor.setBackground(new java.awt.Color(255, 204, 204));
        jCadVendedor.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jCadVendedor);
        jCadVendedor.setBounds(200, 50, 1080, 800);

        btn_master_duvidas.setBackground(new java.awt.Color(204, 204, 255));
        btn_master_duvidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master_duvidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master_duvidasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master_duvidas);
        btn_master_duvidas.setBounds(100, 770, 90, 30);

        btn_master_vendas.setBackground(new java.awt.Color(204, 204, 255));
        btn_master_vendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master_vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master_vendasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master_vendas);
        btn_master_vendas.setBounds(10, 260, 170, 50);

        btn_master_clientes.setBackground(new java.awt.Color(204, 204, 255));
        btn_master_clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master_clientesActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master_clientes);
        btn_master_clientes.setBounds(10, 320, 170, 50);

        btn_master_inicio.setBackground(new java.awt.Color(204, 204, 255));
        btn_master_inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master_inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master_inicioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master_inicio);
        btn_master_inicio.setBounds(10, 100, 170, 50);

        btn_master_cadastro.setBackground(new java.awt.Color(204, 204, 255));
        btn_master_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master_cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master_cadastro);
        btn_master_cadastro.setBounds(10, 210, 180, 40);

        btn_master_cadastro_cliente.setBackground(new java.awt.Color(204, 204, 255));
        btn_master_cadastro_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_master_cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_master_cadastro_clienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_master_cadastro_cliente);
        btn_master_cadastro_cliente.setBounds(10, 160, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-120, -20, 420, 90);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(20, 320, 50, 40);

        jLabel40.setFont(new java.awt.Font("Nunito SemiBold", 1, 25)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Clientes");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(70, 310, 160, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logout.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1200, 0, 60, 50);

        jLabel39.setFont(new java.awt.Font("Nunito SemiBold", 1, 25)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Vendas");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(70, 260, 160, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/master_cadastro.png"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(10, 150, 70, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ususu.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1110, 0, 100, 50);

        jLabel35.setFont(new java.awt.Font("Nunito SemiBold", 1, 25)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Início");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(70, 110, 110, 50);

        jLabel37.setFont(new java.awt.Font("Nunito SemiBold", 1, 25)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Cliente");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(70, 160, 160, 50);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/master_cadastro.png"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(10, 200, 70, 50);

        jLabel41.setFont(new java.awt.Font("Nunito SemiBold", 1, 25)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Vendedor");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(70, 210, 160, 50);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu_1.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(200, 10, 110, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Sell Stock.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(10, 260, 70, 50);

        Cima_Azul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/testttt_background.png"))); // NOI18N
        getContentPane().add(Cima_Azul);
        Cima_Azul.setBounds(200, 0, 1130, 50);

        jLabel38.setFont(new java.awt.Font("Nunito SemiBold", 3, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Dúvidas? Clique aqui");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(10, 760, 190, 50);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_label_png.png"))); // NOI18N
        getContentPane().add(jLabel26);
        jLabel26.setBounds(10, 100, 50, 60);

        jComboBox2.setFont(new java.awt.Font("Nunito SemiBold", 1, 11)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sair" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(1190, 10, 60, 30);

        jComboBox1.setFont(new java.awt.Font("Nunito SemiBold", 1, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trocar de usuário" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(1060, 10, 110, 30);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/testttt_background.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 200, 850);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_master_inicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master_inicioActionPerformed
        tela_inicio telaCadUser = new tela_inicio();
        jCadVendedor.add(telaCadUser);
        telaCadUser.setVisible(true);            
        
        
    }//GEN-LAST:event_btn_master_inicioActionPerformed

    private void btn_master_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master_cadastroActionPerformed
        tela_cadastro_vendedor telaCadUser = new tela_cadastro_vendedor();
        jCadVendedor.add(telaCadUser);
        telaCadUser.setVisible(true);
    }//GEN-LAST:event_btn_master_cadastroActionPerformed

    private void btn_master_duvidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master_duvidasActionPerformed
        tela_duvidas telaCadUser = new tela_duvidas();
        jCadVendedor.add(telaCadUser);
        telaCadUser.setVisible(true);


// TODO add your handling code here:
    }//GEN-LAST:event_btn_master_duvidasActionPerformed

    private void btn_master_vendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master_vendasActionPerformed
        // TODO add your handling code here:
        tela_vendas telaCadUser = new tela_vendas();
        jCadVendedor.add(telaCadUser);
        telaCadUser.setVisible(true);  
    }//GEN-LAST:event_btn_master_vendasActionPerformed

    private void btn_master_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master_clientesActionPerformed
        tela_busca telaCadUser = new tela_busca();
        jCadVendedor.add(telaCadUser);
        telaCadUser.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_master_clientesActionPerformed

    private void btn_master_cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_master_cadastro_clienteActionPerformed
        tela_cadastro_cliente telaCadUser = new tela_cadastro_cliente();
        jCadVendedor.add(telaCadUser);
        telaCadUser.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btn_master_cadastro_clienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cima_Azul;
    private javax.swing.JButton btn_master_cadastro;
    private javax.swing.JButton btn_master_cadastro_cliente;
    private javax.swing.JButton btn_master_clientes;
    private javax.swing.JButton btn_master_duvidas;
    private javax.swing.JButton btn_master_inicio;
    private javax.swing.JButton btn_master_vendas;
    private javax.swing.JDesktopPane jCadVendedor;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    // End of variables declaration//GEN-END:variables
}
