/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Hendrew
 */
public class tela_inicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form tela_inicio
     */
    public tela_inicio() {
        initComponents();
        
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui= (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel28 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(1070, 850));
        getContentPane().setLayout(null);

        jLabel28.setFont(new java.awt.Font("Nunito SemiBold", 1, 19)); // NOI18N
        jLabel28.setText("Rendimentos anuais");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(750, 430, 200, 30);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_grafico2.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 460, 480, 240);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_grafico.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 450, 500, 260);

        jLabel29.setFont(new java.awt.Font("Nunito SemiBold", 1, 19)); // NOI18N
        jLabel29.setText("Rendimentos 2021");
        getContentPane().add(jLabel29);
        jLabel29.setBounds(180, 430, 200, 30);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo - Copia (2).png"))); // NOI18N
        getContentPane().add(jLabel27);
        jLabel27.setBounds(430, -10, 380, 250);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(110, 330, 790, 10);

        jLabel1.setFont(new java.awt.Font("Nunito SemiBold", 1, 48)); // NOI18N
        jLabel1.setText("Início");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 250, 450, 50);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1280, 850));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7);
        jPanel7.setBounds(0, -20, 1100, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
